#This script id for pushing the  idrac  patches  on the  Dell server using  Dellome appliance.
#Below  are the  stages we will follow  end to end  automation.
#STAGE 1: Updating the appliance repository from  DELL centralized Server.
#STAGE 2: Creating the Baseline(with server need to patch).
#STAGE 3: Puashing the patches to  the Idrac  server  without rebooting the nodes.

# We are using a collection module which is not present in the ansible-core module. so we need to  install the  below package  to use this module.
# ansible-galaxy collection install dellemc.openmanage
---
#STAGE 1: 
- name:  Updating the catalog Manager in Dell OME
  hosts: all
  connection: local
  vars:
    hostname: "<OME_IPaddress>"
    username: "<username>"
    password: "<password>"
  tasks:
    - name: Updating the catalog
      dellemc.openmanage.ome_catalog:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        catalog_name: "dell"
        state: "present"
        refresh: yes
        register: ome_update_result
    - name: Displaying the  output of the  result
      debug:
        var: ome_update_result.msg

---
#STAGE 2:
- name: Creating the Baseline in DELL OME
  hosts: all
  connection: local
  gather_facts: false
  vars:
    hostname: "<OME_IPaddress>"
    username: "<username>"
    password: "<password>"
    server_service_tags: [ "tag-1", "tag-2", "tag-3"]
    firmaware_catalog_name: "dell"
    new_baseline_name: "Application_servers"
  tasks:
    - name: creating the baseline using list of server_service_tags
      dellemc.openmanage.ome_firmware_baseline:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        command: "create"
        baseline_name: "{{ new_baseline_name }}"
        baseline_description: "This baseline is for pushing patches application servers"
        catalog_name: "{{ firmaware_catalog_name }}"
        device_service_tags: "{{ server_service_tags }}"
        job_wait: true
        job_wait_timeout: 2400
        register: baseline_creation_job

    - name: Dispalying the results of the baseline_creation_job
      debug:
        vars: baseline_creation_job.output 


